on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Actions of The GitHub'
        run: pwd

      - name: ' Printing  Name'
        run: echo 'Hager Taher'

      - name: 'Printing File Content Before using uses'
        run: ls

      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Printing File Content After using uses'
        run: ls

      - name: "Login to Docker Hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: "Building Docker Hub image"
        run: docker build -t  ${{ secrets.DOCKER_USERNAME }}/myimg .

      - name: "Pushing image to Docker Hub "
        run: docker push  ${{ secrets.DOCKER_USERNAME }}/myimg 
